const StoreData = [
  {
    category: "Uniform",
    id: "1",
    btnid: "1",
    pname: "Girls karate uniform",
    price: "199",
    rating: 4,
    src: "https://originalfightgear.com/wp-content/uploads/2020/03/1-47.jpg",
  },
  {
    category: "Uniform",
    id: "2",
    btnid: "2",
    pname: "Boys karate uniform",
    price: "220",
    rating: 3,
    src: "https://tse4.mm.bing.net/th?id=OIP.wYhT6XPf8ylhekUSB_C5pAAAAA&pid=Api&P=0&h=180",
  },
  {
    category: "Equipment",
    id: "4",
    btnid: "4",
    pname: "gloves",
    price: "233",
    rating: 5,
    src: "https://imfitindia.com/cdn/shop/products/512FXfZ0RPL_600x600.jpg?v=1640157793",
  },
  {
    category: "Shoes",
    id: "29",
    btnid: "29",
    pname: "Traning-Shoes",
    price: "299",
    rating: 5,
    src: "https://tse3.mm.bing.net/th?id=OIP.uiJoyHmLjIpq0SgZZLZYswHaHa&pid=Api&P=0&h=180",
  },
  {
    category: "Uniform",
    id: "3",
    btnid: "3",
    pname: "Yaekwondo uniform",
    price: "299",
    rating: 4,
    src: "https://uniformtailor.in/image/cache/catalog/data/sports%20uniform/karate%20uniforms/Heavyweight%2014%20oz%20Brushed%20Cotton%20Pants%20Red%20Stripe-7%20copy-670x760.jpg",
  },

  {
    category: "Equipment",
    id: "5",
    btnid: "5",
    pname: "gloves",
    price: "399",
    rating: 4,
    src: "https://tse4.mm.bing.net/th?id=OIP.oEyt-RWuOqxJzlpmtWNDnwHaHm&pid=Api&P=0&h=180",
  },

  {
    category: "Equipment",
    id: "6",
    btnid: "6",
    pname: "Target",
    price: "499",
    rating: 4,
    src: "https://i.pinimg.com/originals/f4/5f/47/f45f47b972ef38f073ff328777ab87ea.jpg",
  },
  {
    category: "Equipment",
    id: "7",
    btnid: "7",
    pname: "Punching-Bag",
    price: "459",
    rating: 4,
    src: "https://m.media-amazon.com/images/I/71TagZPjqBL.jpg",
  },
  {
    category: "Shoes",
    id: "28",
    btnid: "28",
    pname: "Runing-Shoes",
    price: "699",
    rating: 3,
    src: "https://tse3.mm.bing.net/th?id=OIP.C4L1dw4Z9XDoz8uyVNWjwAHaHa&pid=Api&P=0&h=180",
  },
  {
    category: "Equipment",
    id: "8",
    btnid: "8",
    pname: "Boxing0kit",
    price: "399",
    rating: 5,
    src: "https://tse2.mm.bing.net/th?id=OIP.bPWuzjpdp3-KHibPtpFhjAHaEb&pid=Api&P=0&h=180",
  },
  {
    category: "Equipment",
    id: "9",
    btnid: "9",
    pname: "Taekwondo-kit",
    price: "899",
    rating: 3,
    src: "https://tse1.mm.bing.net/th?id=OIP.UU4GayqRwQJP1udy47_7kwAAAA&pid=Api&P=0&h=180",
  },
  {
    category: "Equipment",
    id: "10",
    btnid: "10",
    pname: "Boxing Helmet",
    price: "250",
    rating: 3,
    src: "https://rupla.com/wp-content/uploads/2022/06/Pro-sparring-Head-Guard-Red.jpg",
  },
  {
    category: "Equipment",
    id: "11",
    btnid: "11",
    pname: "Kicking Target",
    price: "399",
    rating: 4,
    src: "https://i.pinimg.com/originals/f4/cf/3e/f4cf3e5de2651470ae2726c64c29ba23.jpg",
  },
  {
    category: "Equipment",
    id: "12",
    btnid: "12",
    pname: "Karate Kit",
    price: "488",
    rating: 4,
    src: "https://tse1.mm.bing.net/th?id=OIP.e4w2zBt3mDQCnLjihMsmQgHaHa&pid=Api&P=0&h=180",
  },
  {
    category: "Shoes",
    id: "27",
    btnid: "27",
    pname: "Shoes",
    price: "999",
    rating: 4,
    src: "https://tse2.mm.bing.net/th?id=OIP.AHNlYS95YJM1C9GakLLRLwEgDY&pid=Api&P=0&h=180",
  },
  {
    category: "Equipment",
    id: "13",
    btnid: "13",
    pname: "Karate gloves",
    price: "99",
    rating: 5,
    src: "https://www.pride.shop/images/thumbs/0000577_r620-arawaza-wkf-karate-gloves.jpeg",
  },
  {
    category: "Equipment",
    id: "14",
    btnid: "14",
    pname: "Karate leg-guard",
    price: "599",
    rating: 5,
    src: "https://arawaza.com/wp-content/uploads/2019/10/shin-pads-approved-wkf-arawaza-1024x1024.jpg",
  },
  {
    category: "Equipment",
    id: "15",
    btnid: "15",
    pname: "Mouth-guard",
    price: "499",
    rating: 4,
    src: "https://www.arawazashop.eu/wp-content/uploads/2017/08/AZZ_Mouth_guard_transparent.jpg",
  },
  {
    category: "Uniform",
    id: "16",
    btnid: "16",
    pname: "Uniform",
    price: "199",
    rating: 5,
    src: "https://tse2.mm.bing.net/th?id=OIP.4c5qiRvyJuWk_U68u47-9gHaHa&pid=Api&P=0&h=180",
  },
  {
    category: "Uniform",
    id: "17",
    btnid: "17",
    pname: "Uniform",
    price: "399",
    rating: 5,
    src: "https://i5.walmartimages.com/asr/9d4b5d5a-593c-4984-b7fd-ddf085aefa1e.e6c05b94f2d7d2e2247232bd44465d30.jpeg",
  },
  {
    category: "Uniform",
    id: "18",
    btnid: "18",
    pname: "Uniform",
    price: "899",
    rating: 5,
    src: "https://i5.walmartimages.com/asr/1095dbae-fd75-42f7-9d24-ff7595a07690.7644800bc5768f832a7dbe831711d7f3.jpeg",
  },
  {
    category: "Uniform",
    id: "19",
    btnid: "19",
    pname: "Kung-fu Uniform",
    price: "499",
    rating: 4,
    src: "https://totalmartialartsupplies.com/content/images/thumbs/0003505_short-sleeve-kung-fu-uniform-poly-cotton.jpeg",
  },
  {
    category: "Uniform",
    id: "20",
    btnid: "20",
    pname: "Wing-chun Uniform",
    price: "599",
    rating: 5,
    src: "https://www.moderndancedress.com/image/cache/catalog/products_2018/new-embroidery-tai-chi-suits-cotton-wu-shu-clothes-kung-fu-uniform-morning-exercise-the-martial-arts-performance-wear-clothing-tai-chi-clothing-tai-chi-md00047-900x900.jpg",
  },
  {
    category: "Shoes",
    id: "26",
    btnid: "26",
    pname: "Shoes",
    price: "899",
    rating: 4,
    src: "https://cdn.shopify.com/s/files/1/2202/0499/products/ADITPR-WHT-BLK-01.jpg?v=1575696843",
  },
  {
    category: "Uniform",
    id: "21",
    btnid: "21",
    pname: "Wing-chun Uniform",
    price: "399",
    rating: 5,
    src: "https://tse2.mm.bing.net/th?id=OIP.e0p025dod-Je9FzNzx7COQHaI3&pid=Api&P=0&h=180",
  },
  {
    category: "Uniform",
    id: "22",
    btnid: "22",
    pname: "kung-fu Uniform",
    price: "499",
    rating: 4,
    src: "https://i.pinimg.com/originals/d8/d7/70/d8d7704673e65611092fcc55e7b246f7.jpg",
  },
  {
    category: "Uniform",
    id: "23",
    btnid: "23",
    pname: "Wing-chun Uniform",
    price: "549",
    rating: 3,
    src: "https://www.totalmartialartsupplies.com/content/images/thumbs/0002197_tai-chi-washable-satin-silk-uniform.jpeg",
  },
  {
    category: "Uniform",
    id: "24",
    btnid: "24",
    pname: "Combo Uniform",
    price: "529",
    rating: 5,
    src: "https://images-na.ssl-images-amazon.com/images/I/71A4G25uYrL._AC_UL1500_.jpg",
  },
  {
    category: "Shoes",
    id: "25",
    btnid: "25",
    pname: "Shoes",
    price: "999",
    rating: 3,
    src: "https://tse1.mm.bing.net/th?id=OIP.nVbSkGG4fTPgNAKnue7RuQHaHa&pid=Api&P=0&h=180",
  },
  {
    category: "Shoes",
    id: "30",
    btnid: "30",
    pname: "Boxing-Shoes",
    price: "899",
    rating: 5,
    src: "https://tse3.mm.bing.net/th?id=OIP.X-O6mhY1MqZW-ToFA2F0JgHaHa&pid=Api&P=0&h=180",
  },
];

export default StoreData;
